### ISSUE TITLE
IP Adresse im ESR-Receiver

### ISSUE THREAD

**Issue by olivermarchand** [luklanis/ps-scan#1]
Hallo,

ich weiss nicht welche IP Adresse ich im Receiver eingeben soll? Die von meinem Android Phone? Wie finde ich die heraus?

Gruss & Danke,
Oliver

**Comment by luklanis** [comment]
Hallo Oliver

Ja, es ist die IP Adresse deines Android Phone wenn du eine Verbindung mit dem WLAN hast.
Wie unter https://github.com/luklanis/ps-scan/blob/master/android/assets/html-de/srmode.html (Ist auch in der App selber in der Hilfe zu finden) beschrieben, sollte die IP Adresse unten rechts angezeigt werden, sobald der Beleglesermodus über die Einstellungen aktiviert wurde.

Gruss
Lukas

**Comment by olivermarchand** [comment]
Hoi Lukas,

Funktioniert - super. Danke für den Support! Das Problem mit der Hilfe
war übrigens, dass ich sie iwrklich aus Versehen weggeklickt hatte und
dann nicht mehr aufrufen konnte. Ich hatte wie ich nämlich jetzt
festgestellt habe mehrfach übersehen, dass man in der Hilfe scrollen
kann. Ich dachte immer, dass diese sehr allgemeine Nachricht alles ist
was man dort finden kann. Vielleicht kannst Du das Inhaltsverzeichnis
nach oben nehmen?

Gruss,
Oliver

Am 20. Juli 2012 08:09 schrieb Lukas Landis
reply@reply.github.com:

> Hallo Oliver
> 
> Ja, es ist die IP Adresse deines Android Phone wenn du eine Verbindung mit dem WLAN hast.
> Wie unter https://github.com/luklanis/ps-scan/blob/master/android/assets/html-de/srmode.html (Ist auch in der App selber in der Hilfe zu finden) beschrieben, sollte die IP Adresse unten rechts angezeigt werden, sobald der Beleglesermodus über die Einstellungen aktiviert wurde.
> 
> Gruss
> Lukas
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/luklanis/ps-scan/issues/1#issuecomment-7123045

## 

Oliver Marchand

Wunderlistr. 45
CH-8037 Zürich
home: +41 44 3804948
mobile: +41 78 8032102
email: oliver.marchand@gmail.com
skype: olivermarchand

email@work: oliver.marchand@fam.ch
phone@work: +41 44 2842446

**Comment by luklanis** [comment]
Hoi Oliver

Danke für den Hinweis! Werde ich in einer Folgeversion anpassen!

Beste Grüsse!
Lukas
